### ISSUE TITLE
Error when rendered with only one slide

### ISSUE THREAD

**Issue by maxpblum** [jl-/react-slide-deck#4]
Hi again! We're getting close to deploying our new app that uses this component—very excited about it. We're A/B testing various versions of it, though, including one that doesn't include multiple slides, and it would be awesome if we didn't have to conditionally wrap our slides in the `<SlideDeck>` component based on how many there are. We tried having only one slide, though, and we got this error: 
![image](https://cloud.githubusercontent.com/assets/7944695/11659993/f60f37be-9d98-11e5-8591-59fca02b9d2b.png)

The error pops up from this line: https://github.com/jl-/react-slide-deck/blob/master/src/deck.js#L275

Do you think it would be possible to make the component handle the one-slide case gracefully? We can work around it if not, but if it's an easy fix, it would be so great.

Thank you, again, for all your work!!

**Comment by jl-** [comment]
Thanks @maxpblum , I really should have added unit test support. I think it has been fixed with [this commit](https://github.com/jl-/react-slide-deck/commit/b9e4cc7456029301127dc70de6eda2c276f5aa8d#diff-07064589f93f222fd80baaf6635b3f37R259). Is it ok that you replace  your local  `react-slide-deck/dist/deck.js` with this [new build](https://github.com/jl-/react-slide-deck/blob/master/dist/deck.js) and run the test again to see if it passed. If that went well, I will make a release right away. Sorry again for lacking of test cases.
